name: 'pr-comment'
description: 'Adds PR changes as comment'
author: 'Your name or organization here'

# Define your inputs here.
inputs:
  owner:
    description: 'The owner if the repository (user or org)'
    required: true

  repo:
    description: 'The repository name',
    requiresd: true
  
  pr_number:
    description: 'The number of the pull request'
    required: true
  
  token:
    description: 'The token to use to access the the GITHUB API'
    required: true


runs:
  using: 'node16'
  main: dist/index.js
